services:
  appointment_db:
    container_name: db_appointment
    image: postgres:16.4
    volumes:
      - postgresappointment:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_USER=appointment_user
      - POSTGRES_PASSWORD=1234sql
      - POSTGRES_DB=appointment_db_pg

  appointment_app:
    container_name: app_appointment
    build: .
    volumes:
      - .:/usr/src/app
      - postgresappointment:/var/lib/postgresql/data
    ports:
      - 8000:8000
    depends_on:
      - appointment_db
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: python manage.py runserver 0.0.0.0:8000
    # launch this with docker you need to run python 
    # manage.py makemigrations "name_app" for creating migrations

volumes:
  postgresappointment: