# Generated by Django 5.1.2 on 2024-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('lastname', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(blank=True, default='None', max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('description', models.CharField(blank=True, default='anything', max_length=30, null=True)),
                ('register', models.DateField(auto_now_add=True)),
                ('calendar', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_registerdate',
                'managed': True,
            },
        ),
    ]
